Coloured logging, respect IOSDEVICEMANGER_PATH

diff --git a/client/iOSDeviceManager b/client/iOSDeviceManager
--- a/client/iOSDeviceManager
+++ b/client/iOSDeviceManager
@@ -12,17 +12,35 @@ function alive {
   echo $(curl -q "${HEALTH}" 2>/dev/null)
 }
 
+function error {
+  if [ "${TERM}" = "dumb" ]; then
+    echo "ERROR: $1"
+  else
+    echo "$(tput setaf 1)ERROR: $1$(tput sgr0)"
+  fi
+}
+
+if [ ! -z "${IOSDEVICEMANAGER_PATH}" ]; then
+  SERVER_BIN="${IOSDEVICEMANAGER_PATH}"
+fi
+
+if [ ! -e "${SERVER_BIN}" ]; then
+   error "Can not find iOSDeviceManagerServer"
+   error "Ensure it is installed or set IOSDEVICEMANAGER_PATH=/path/to/iOSDeviceManagerServer"
+   exit 1
+fi 
+
 if [ -z "$(alive)" ]; then
   BIN=$(which "${SERVER_BIN}" || true)
   if [ -z "${BIN}" ]; then
-    echo "$SERVER_BIN is not installed!"
-    exit 1
+    error "$SERVER_BIN is not installed!"
+    exit 2
   fi
   exec $BIN &
   sleep 2
   if [ -z "$(alive)" ]; then
-    echo "$SERVER_BIN failed to start!"
-    exit 2
+    error "$SERVER_BIN failed to start!"
+    exit 3
   fi
 fi
 
